### ISSUE TITLE
Behavior modal javascript highlight bug

### ISSUE THREAD

**Issue by abemscac** [samatechtw/pubstudio-builder#11]
The problems only occur when the text is being copied from a outer source (any place that's not the editor itself), and is pasted to the editor by using "ctrl/alt + a" -> "ctrl/alt + v" (select all then paste).

https://github.com/samatechtw/pubstudio-builder/assets/59676941/aa8d5df7-d2ec-4da7-b43d-e93b52ad215d

In the above video, new line characters are ignored after paste, and the edit history is cleared (undo/redo don't work anymore).

If the content is appended to the editor instead of replacing the whole content with "ctrl/alt + a" -> "ctrl/alt + v" , the editor will work fine.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/a1eb52ad-5915-40f8-a3aa-f9353e6c2da2

However, if the select all action is performed with mouse click or shift + arrow key, the problems will not occur.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/b7f35c85-0b2f-414f-99bd-b69763e96e3c

What's even more strange is, if the text is copied from a ProseMirror editor, pasting it with "ctrl/alt + a" -> "ctrl/alt + v" won't cause any problem. New line characters are preserved, and edit history still works.

https://github.com/samatechtw/pubstudio-builder/assets/59676941/6f779838-a291-4dd9-84f3-0005280ad48c

From the log it seems that the selection produced by "ctrl/alt + a" and "mouse click/shift + arrow key" are programmatically different, even though they look the same on the UI. In short, the editor will broke when `newState = prosemirrorSetup(...)` is run. Maybe the only way to solve this problem is to modify the view state instead of creating a new one.

**Comment by sampullman** [comment]
Got it! Thanks for the detailed report.
