### ISSUE TITLE
Open reusable style page after undo

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#159]
When undoing a command that edits a reusable style, the editor right menu should show the style editing menu.

When undoing a command while the reusable style editing menu is open, and the previous command was not related to reusable styles, the menu should be hidden. Basically, the right menu should return to the correct context during undo/redo.

**Comment by sampullman** [comment]
@abemscac I'm not sure I explained this correctly, but it's the issue you brought up on Monday. I added it to the backlog, but if it's easy to take care of we can prioritize it.

**Comment by abemscac** [comment]
Got it! I think the explanation is clear, thank you!
