### ISSUE TITLE
Mixin breakpoint styles not showing in editor

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#182]
Editing reusable styles in non-default breakpoints appears to work correctly, but the resulting styles aren't displayed in the editor.

In preview and live mode, the styles are shown correctly.

https://github.com/samatechtw/pubstudio-builder/assets/550982/33d7d0bd-cfdd-44da-acb2-6c97e1e1b98e

**Comment by sampullman** [comment]
@abemscac this one might be difficult to reproduce, I remember that I adjusted some of the breakpoint widths, but I'm not sure if it's related.

**Comment by abemscac** [comment]
Got it. I'll take a look at all the comments & changes you made recently and try to fix this bug, if it still persists, thank you!
