### ISSUE TITLE
update_key date format incompatible

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#200]
See discussion starting here: https://github.com/samatechtw/pubstudio-builder/pull/199#issuecomment-1876247014

**Comment by ClaireMao1996** [comment]
We are already returning `JsDate` in the response! This is the result of my test after modifying the regex, and it seems to be working.


https://github.com/samatechtw/pubstudio-builder/assets/101389820/dddc0084-a234-4921-a525-0f2ad1d43a19

**Comment by sampullman** [comment]
Oh, got it. I must have forgotten something about how we handle dates. In that case, adjusting the regex should be fine 👍

**Comment by ClaireMao1996** [comment]
So, currently, the date format sent from the backend (e.g., 2024-01-04T04:15:53.000000Z) will be parsed in the frontend into a 2 digit millisecond like `2024-01-04T04:15:53Z`, and then this string is sent to `get-site` or `update-site`, right?

**Comment by ClaireMao1996** [comment]
Oh, I've noticed that I didn't add validation for the `update_key` in the query of `get-site`. So, I didn't catch this issue before. Should we also include this check in get-site?

**Comment by sampullman** [comment]
Yeah, that seems like what's happening. We can add the validation to both.
