### ISSUE TITLE
Some UI issues

### ISSUE THREAD

**Issue by abemscac** [samatechtw/pubstudio-builder#202]
Site template for reproducing bugs (the selected border might look different due to my under development code for #164):

[pub-Splash Page 120240104-165726.json](https://github.com/samatechtw/pubstudio-builder/files/13828114/pub-Splash.Page.120240104-165726.json)

1. #205

2. #206

3. #207

4. #208 

5. #209

6. #210

**Comment by sampullman** [comment]
Thanks! I'll split this into a few different issues. The preview input value bug may be difficult to fix, but I think it's less critical than the others.
