### ISSUE TITLE
Pseudo styles not shown as inherited

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#205]
When switching to another pseudo class, styles inherited from the default pseudo class should show inheritance info instead of a remove button.

Site example:
[230107_pseudo-bug.json](https://github.com/samatechtw/pubstudio-builder/files/13853534/230107_pseudo-bug.json)

https://github.com/samatechtw/pubstudio-builder/assets/59676941/d9e61eec-d192-4a4d-abf8-aa3972c07438

**Comment by sampullman** [comment]
@abemscac I have an idea about how to solve this, but I'm not sure if it's over-complicated.

It seems like `computeComponentFlattenedStyles` needs to include the pseudo style when used in the component/style menu, in order to calculate `inheritedFrom`. But I don't think that information is necessary when called from `getPageStyle` or `findStyles`, so maybe there's a more efficient way (split up the function so only the required data is returned)?

**Comment by abemscac** [comment]
Got it, splitting them up makes sense to me.
I'll take a look at this today, thank you!
