### ISSUE TITLE
Some suggestions for editor

### ISSUE THREAD

**Issue by ClaireMao1996** [samatechtw/pubstudio-builder#216]
In the process of developing templates, I encountered some issues related to the editor:

1. When I input a string such as `$19.99 / month` it automatically converted to a link. I believe this happens because it contains `.` and `/` leading the system to interpret it as a link

https://github.com/samatechtw/pubstudio-builder/assets/101389820/bd281e1f-0d28-46a6-9f01-2c8907aaeb80

2. When I try to create a new behavior, the content within `helpers` is obstructed.

https://github.com/samatechtw/pubstudio-builder/assets/101389820/6dfbfe3f-8953-40e7-ab65-9654cd9de6d1

**Comment by sampullman** [comment]
Got it, thanks! I think the second issue is solved in the `main` branch, we just need to trigger a deploy. The first one seems like a regex issue when detecting links, maybe @abemscac knows a quick fix!
