### ISSUE TITLE
Adjust get-site API permissions

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#342]
Similar to `get_current_site`, `get_site` should only return content fields when the requester is anonymous. Also, the versions endpoint should not be accessible to anonymous requesters.

### Tasks
- Update `get_site` to only return content fields when the requester is anonymous
- Remove anonymous requester from `GET /sites/:site_id/versions/:version_id`
- Update API tests

**Comment by ClaireMao1996** [comment]
Hi @sampullman ,

I want to make sure in `get_site.rs`, `with_editor` means `user != Anonymous`?

Thanks!

**Comment by sampullman** [comment]
Oh no! I just realized this conflicts with another issue I completed for drafts/publishing.

I realized we aren't using get_site for anonymous users at all, so I removed all that capability. That means we no longer need to worry about adjusting these permissions.

**Comment by ClaireMao1996** [comment]
Oh yeah! But for the endpoint `GET /sites/:site_id/versions/:version_id` we still want to remove anonymous requester?

**Comment by sampullman** [comment]
For that one I'm not quite sure. I'm starting to implement draft preview links, so it might be used there. If not, I can remove the anonymous permission and update the tests.

**Comment by ClaireMao1996** [comment]
Got it, I'll move on to the next issue.
