### ISSUE TITLE
Memory cache for get-current-site requests

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#343]
Add a memory cache for get-current-site requests, which only includes content fields: `id, name, version, context, defaults, pages, created_at, updated_at`.

### Tasks
- Add memory cache for get-current-site data
- Reset cache (either clear it or include a "dirty" field) when `update-site` is called, for the currently published site-version
- Reset cache when a new site version is published

**Comment by ClaireMao1996** [comment]
Hi @sampullman ,

In this feature, `get-current-site` always return from cache? And cache data will be updated when `update_site` & `new site version is published`?

**Comment by sampullman** [comment]
Yeah, that's the plan!

But the logic might be slightly more complicated after my next PR, since we only need to update the cache if the live version changes.

The logic for updating the cache will be something like:
- Update cache if new version is published (this copies the data from the draft to the live version)
- Update the cache if `update_site` is called and there is no draft. We shouldn't change the cache if there is a draft, because `get_current_site` should always return the live version.

**Comment by sampullman** [comment]
A couple of notes from the call:
- Don't need to cache preview versions in `get_current_site` (e.g. when `p` query param is present)
- Try to avoid any database calls when returning cached version (maybe need to cache site metadata as well)
- Make sure to reset cache when site is published or updated

**Comment by ClaireMao1996** [comment]
Thanks! 
I think it might be worth caching the site metadata, as it's used in several places within `get_current_site`!

**Comment by ClaireMao1996** [comment]
However, for operations like `get_site_id_by_hostname`, we inevitably need to fetch it every time, as our endpoint is `/sites/current`, and we retrieve the `site_id` based on the hostname.

**Comment by sampullman** [comment]
True, I was just thinking about that. 

There might be a solution to this - first, the data can be wrapped in `Arc` in order to avoid cloning it when `cache.get()` is called as described [here](https://github.com/moka-rs/moka?tab=readme-ov-file#avoiding-to-clone-the-value-at-get). Then, since we already have an `Arc`, maybe the cache can be `domain -> Arc<SiteData>` to avoid any DB lookups. So each site could have one key per domain that points to the same data. This architecture probably requires that the ID is keyed to the site data as well, in order to check whether the data exists in the cache when adding a new domain entry.

Another similar solution is two caches, one is `domain -> site_id`, the other is `site_id -> site_data`.

Either way it's somewhat complicated, but the main point of the feature is to avoid hitting the database.

**Comment by ClaireMao1996** [comment]
Got it! I’ll look into these two solutions!
