### ISSUE TITLE
Add option to remove draft

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#369]
Add an option to remove the draft from a site. This is not necessarily a common need for users, but it's convenient when testing features manually.

### Tasks

- [ ] Draft delete endpoint `/sites/:site_id/actions/delete_draft`

**Comment by sampullman** [comment]
@ClaireMao1996 I haven't thought through the UI yet, I'll try to take care of it once the delete endpoint is ready!

**Comment by ClaireMao1996** [comment]
For this issue, I'd like to confirm that we'll first check if there's a draft like we do with `create_draft`. If so, I'll delete the last version, right?

**Comment by sampullman** [comment]
Yeah, that should be enough! I was considering whether we should make sure the latest version is published in order to avoid losing data.

Maybe it can be an option on the frontend that's checked by default 🤔

In that case, the frontend could handle calling the publish endpoint first.

**Comment by sampullman** [comment]
Yes, something like that will work!
