### ISSUE TITLE
CSS pseudostyle editor bug

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#66]
When a non-default pseudo style is selected in the editor, all the normal stylings disappear.

https://github.com/samatechtw/pubstudio-builder/assets/550982/96f6843f-861c-4640-81b5-b31e047de303

**Comment by sampullman** [comment]
@abemscac I'll take a look at this one when I get the chance, but if you know an easy solution you can fix it first!

**Comment by abemscac** [comment]
Got it, I'll try to fix this now!
