### ISSUE TITLE
Image caption component builtin

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#70]
Add a component for an image with a caption.

**Comment by abemscac** [comment]
Hi @sampullman 

Is this component referring to the [`<figure>` and `<caption>`](https://www.w3schools.com/tags/tag_figure.asp) tag in HTML? I've never seen someone using those tags, but they seem to match the description of this issue.

**Comment by sampullman** [comment]
Technically those are probably the right tags to use. But I think it's kind of complicated in the builder, because the user probably doesn't know which components they should or shouldn't add to a figure. For now I think it's better to stick to regular `div` as the wrapper and reuse the `img` and `text` builtins. Users who really care about the semantics can add `ARIA` roles.

**Comment by abemscac** [comment]
Got it, thanks for the clarification!
