### ISSUE TITLE
Tab and shift-tab to change selection

### ISSUE THREAD

**Issue by sampullman** [samatechtw/pubstudio-builder#88]
When a component is selected in the editor and the tab key is pressed, select the next component. The logic is:

1. If the component has 1 or more children, select the first one
2. If the component's parent has a "next" child, select it
3. Otherwise apply the 2. logic to the parent
4. Last component on the page - do nothing

When shift-tab is pressed, select the previous component (reverse of above logic).

**Comment by abemscac** [comment]
Hi @sampullman 

I have a question regarding selecting the previous component. Consider this tree:

```
- A
  - B
    - C
      - D
      - E
    - F
  - G
```
  
If we were to select the previous component of `F`, should it be `E` or `C` that gets selected 🤔?

**Comment by sampullman** [comment]
It should be `E`, the order would be `F -> E -> D -> C`

**Comment by abemscac** [comment]
Got it, thanks for the clarification!
